# Stage 1: Build
FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Production
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /usr/src/app/dist ./dist
# Copy cron jobs if needed or any other static assets not in dist

USER node

EXPOSE 5000

CMD ["node", "dist/index.js"]
